repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: src/xmlutils/resources
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-yaml
      - id: detect-private-key
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.7.0"
    hooks:
      - id: isort
        types: [file, python]
        exclude: |
          (?x)^(
            api/accounts/views.py|
            api/accounts/urls.py|
          )$

  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
        types: [file, python]
        exclude: |
          (?x)^(
            cain/settings.py|
            migrations/|
            api/accounts/migrations/|
            api/accounts/views.py|
            api/accounts/urls.py|
          )$
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: |
          (?x)^(
            cain/settings.py|
            migrations/|
            api/accounts/migrations/|
          )$
        additional_dependencies:
          [
            "flake8-comprehensions",
            "flake8-debugger",
            "flake8-eradicate",
            "flake8-mutable",
          ]
