# Generated by Django 4.2.10 on 2024-02-18 19:02

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterprisesModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("cnpj", models.BigIntegerField(unique=True)),
                ("corporate", models.CharField(max_length=150, unique=True)),
                ("fantasy", models.CharField(max_length=150, unique=True)),
                (
                    "associates",
                    models.ManyToManyField(
                        related_name="work_for", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
