# Generated by Django 4.2.10 on 2024-02-18 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprisesmodel",
            name="cnpj",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(14)],
            ),
        ),
    ]
