# Generated by Django 4.2.10 on 2024-02-20 01:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enterprises", "0002_alter_enterprisesmodel_cnpj"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprisesmodel",
            name="situation",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=15
            ),  # noaq: E501
            preserve_default=False,
        ),
    ]
